# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    - run: npm run build
    - name: "build Clone to gitee"
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: 
          git@gitee.com:imohuan/resume.git
        ssh_private_key: 
          ${{ secrets.GITHUBCLONEGITEE }}
